# Generated by Django 5.0.6 on 2024-05-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_countries_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countries',
            table='Count',
        ),
    ]
