# Generated by Django 5.0.6 on 2024-05-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_alter_countries_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countries',
            table='Country',
        ),
    ]
